// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrangeTv.Api.Data;

#nullable disable

namespace OrangeTv.Api.Data.Migrations
{
    [DbContext(typeof(OrangeTvDbContext))]
    [Migration("20260409024035_AddWatchHistory")]
    partial class AddWatchHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("OrangeTv.Api.Data.Entities.AppEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChromeProfileSegment")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSessionEndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastSessionExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LaunchUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionFreshness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("apps", (string)null);
                });

            modelBuilder.Entity("OrangeTv.Api.Data.Entities.LaunchSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpawnError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("launch_sessions", (string)null);
                });

            modelBuilder.Entity("OrangeTv.Api.Data.Entities.MediaItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FileModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastScanError")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastScannedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailRelativePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("LastScannedAtUtc");

                    b.ToTable("media_items", (string)null);
                });

            modelBuilder.Entity("OrangeTv.Api.Data.Entities.MediaResumeEntity", b =>
                {
                    b.Property<Guid>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("LastEventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastLaunchSessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastPlayedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("PositionSeconds")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("MediaItemId");

                    b.HasIndex("LastPlayedAtUtc");

                    b.ToTable("media_resume", (string)null);
                });

            modelBuilder.Entity("OrangeTv.Api.Data.Entities.SettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("OrangeTv.Api.Data.Entities.WatchEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<byte>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LaunchSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MediaItemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<double?>("PositionSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("LaunchSessionId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("MediaItemId", "OccurredAtUtc");

                    b.ToTable("watch_events", (string)null);
                });

            modelBuilder.Entity("OrangeTv.Api.Data.Entities.LaunchSessionEntity", b =>
                {
                    b.HasOne("OrangeTv.Api.Data.Entities.AppEntity", null)
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrangeTv.Api.Data.Entities.MediaItemEntity", null)
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("OrangeTv.Api.Data.Entities.MediaResumeEntity", b =>
                {
                    b.HasOne("OrangeTv.Api.Data.Entities.MediaItemEntity", null)
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrangeTv.Api.Data.Entities.WatchEventEntity", b =>
                {
                    b.HasOne("OrangeTv.Api.Data.Entities.AppEntity", null)
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OrangeTv.Api.Data.Entities.LaunchSessionEntity", null)
                        .WithMany()
                        .HasForeignKey("LaunchSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OrangeTv.Api.Data.Entities.MediaItemEntity", null)
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
